PiQuest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from wagtail.core import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.contrib.sitemaps.views import sitemap
from puput import urls as puput_urls
from classroom.views import classroom
from digiwiz import urls as course

admin.site.site_header = 'PiQuests Admin'
admin.site.site_title = 'PiQuests Site Admin'

urlpatterns = [
    path('', include('user.urls', namespace='piquest-auth')),
    path('', include('main.urls', namespace='main')),
    path('project/', include('projects.urls', namespace='project')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about-us/', classroom.about, name='about_us'),
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('todo/', include('todo.urls', namespace="todo")),
    path('course/', include(course)),
    path("badges/", include("pinax.badges.urls", namespace="pinax_badges")),
    path("announcements/", include("pinax.announcements.urls", namespace="pinax_announcements")),
    path(
        route='blog_admin/',
        view=include(wagtailadmin_urls)
    ),
    path(
        route='documents/',
        view=include(wagtaildocs_urls)
    ),
    re_path(r'', include(puput_urls)),
    re_path(
        route='',
        view=include(wagtail_urls)
    ),
    path(
        route='sitemap.xml',
        view=sitemap
    ),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

classroom/urls.py
from django.urls import include, path
from .views import classroom, staff, students, teachers

urlpatterns = [
    path('', classroom.class_index, name='home'),

    path('staff/', include(([
        path('', staff.dashboard, name='dashboard'),
        path('account/', staff.account, name='account'),
        #    path('account/change-password/',
        #         staff.ChangePassword.as_view(), name='change_password'),
        path('admin-accounts/', staff.AdminListView.as_view(), name='admin_list'),
        path('admin-accounts/add/',
             staff.AdminCreateView.as_view(), name='admin_add'),
        path('admin-accounts/<int:pk>/delete/',
             staff.deactivate_admin, name='admin_deactivate'),
        path('course-requests/', staff.CourseRequestsView.as_view(),
             name='course_requests'),
        path('course-requests/accept/<int:course_pk>/',
             staff.accept_course, name='accept_course'),
        path('course-requests/reject/<int:course_pk>/',
             staff.reject_course, name='reject_course'),
        path('courses/', staff.CourseListView.as_view(), name='course_list'),
        path('courses/<int:course_pk>/delete/',
             staff.delete_course, name='course_delete'),
        path('get-user-activities/', staff.get_user_activities,
             name='get_user_activities'),
        path('get-course-status/', staff.get_course_status,
             name='get_course_status'),
        path('students/', staff.StudentListView.as_view(), name='student_list'),
        path('students/<int:pk>/delete/',
             staff.deactivate_student, name='teacher_deactivate'),
        path('subjects/', staff.SubjectListView.as_view(), name='subject_list'),
        path('subjects/add/', staff.SubjectCreateView.as_view(), name='subject_add'),
        path('subjects/<int:pk>/', staff.SubjectUpdateView.as_view(),
             name='subject_change'),
        path('subjects/<int:pk>/delete/',
             staff.delete_subject, name='subject_delete'),
        path('teachers/', staff.TeacherListView.as_view(), name='teacher_list'),
        path('teachers/<int:pk>/delete/',
             staff.deactivate_teacher, name='teacher_deactivate'),
        path('user-log/', staff.UserLogListView.as_view(), name='user_log_list'),
        path('user-log/<int:pk>/delete/',
             staff.delete_log, name='user_log_delete')
    ], 'classroom'), namespace='staff')),

    path('student/', include(([
        path('', students.MyCoursesListView.as_view(), name='mycourses_list'),
        #    path('change-password/', students.ChangePassword.as_view(),
        #         name='change_password'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/',
             students.take_quiz, name='take_quiz'),
        path('enroll/<int:pk>/', students.enroll, name='enroll'),
        path('interests/', students.StudentInterestsView.as_view(),
             name='student_interests'),
        path('profile/', students.profile, name='profile'),
        path('taken/', students.TakenQuizListView.as_view(),
             name='taken_quiz_list'),
        path('taken/<int:taken_pk>/quiz/<int:quiz_pk>/',
             students.taken_quiz_result, name='taken_quiz_detail'),
        path('unenroll/<int:pk>/', students.unenroll, name='unenroll'),
        path('view-file/<int:pk>/', students.file_view, name='view_file')
    ], 'classroom'), namespace='students')),

    path('teacher/', include(([
        path('', teachers.CourseListView.as_view(), name='course_change_list'),
        path('ajax/load-lessons/', teachers.load_lessons,
             name='ajax_load_lessons'),
        #    path('change-password/', teachers.ChangePassword.as_view(),
        #         name='change_password'),
        path('course/add/', teachers.CourseCreateView.as_view(), name='course_add'),
        path('course/<int:pk>/', teachers.CourseUpdateView.as_view(),
             name='course_change'),
        path('course/<int:pk>/delete/',
             teachers.delete_course, name='course_delete'),
        path('course/<int:course_pk>/lesson/<int:lesson_pk>/',
             teachers.edit_lesson, name='lesson_edit'),
        path('course/<int:course_pk>/lesson/<int:lesson_pk>/delete/',
             teachers.delete_lesson, name='lesson_delete'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/',
             teachers.edit_quiz, name='quiz_edit'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/question/add/',
             teachers.add_question, name='question_add'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/',
             teachers.edit_question, name='question_change'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/delete/',
             teachers.delete_question, name='question_delete'),
        path('enrollment-requests/', teachers.EnrollmentRequestsListView.as_view(),
             name='enrollment_requests_list'),
        path('enrollment-requests/accept/<int:taken_course_pk>', teachers.accept_enrollment,
             name='enrollment_accept'),
        path('enrollment-requests/reject/<int:taken_course_pk>', teachers.reject_enrollment,
             name='enrollment_reject'),
        path('files/', teachers.FilesListView.as_view(), name='file_list'),
        path('files/add/', teachers.add_files, name='file_add'),
        path('files/<int:file_pk>/delete/', teachers.delete_file,
             name='delete_file'),
        path('lesson/', teachers.LessonListView.as_view(), name='lesson_list'),
        path('lesson/add/', teachers.add_lesson, name='lesson_add'),
        path('lesson/<int:lesson_pk>/delete/', teachers.delete_lesson_from_list,
             name='delete_lesson_from_list'),
        path('profile/', teachers.profile, name='profile'),
        path('quiz/', teachers.QuizListView.as_view(), name='quiz_list'),
        path('quiz/add/', teachers.add_quiz, name='quiz_add'),
        path('quiz/<int:quiz_pk>/delete/', teachers.delete_quiz_from_list,
             name='delete_quiz_from_list'),
        path('quiz/<int:quiz_pk>/delete/',
             teachers.delete_quiz, name='quiz_delete'),
        path('quiz/<int:pk>/results/',
             teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:quiz_pk>/results/<int:student_pk>/taken/<int:taken_pk>',
             teachers.quiz_result_detail, name='quiz_result_detail')
    ], 'classroom'), namespace='teachers')),
]

main/urls.py
from django.urls import path
from .views import HomePageView, PrivacyPageView, pi_validation
from quiz.views import (CategoryDetail, CategoriesListView, CategoryCreate,
                        CategoryUpdate, CategoryDelete)

app_name = 'main'

urlpatterns = [
    path('', HomePageView.as_view(), name='home_page'),
    path('validation-key.txt', pi_validation, name='pi_validation'),
    path('privacy/', PrivacyPageView.as_view(), name='privacy_page'),
    path('category/', CategoriesListView.as_view(), name='category_list'),
    path('category/create/', CategoryCreate.as_view(), name='category_create'),
    path('category/<slug>/update/',
         CategoryUpdate.as_view(), name='category_update'),
    path('category/<slug>/delete/',
         CategoryDelete.as_view(), name='category_delete'),
    path('category/<slug>/', CategoryDetail.as_view(), name='category_detail'),
]

templates/403_csrf.html
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from bdevs.net/edulab/edulab/404.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 12 May 2019 04:51:17 GMT -->
<head>
    <!--========= Basic Page Needs =========-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!--========== Specific Meta ==========-->
    <meta name="description" content="Online Education template Based on HTML5.">
    <meta name="keywords" content="HTML5, Template, Design, Development, education, edulab, online cources, training, online education, best education template">

    <!--======== Page Title===========-->
    <title>403 Forbidden</title>

    <!--========== Favicons =========-->
    <link rel="shortcut icon" href="/static/images/DW.png">

    <!--======== Font icon Css ============-->
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/themify-icons.css" rel="stylesheet">

    <!--======= Bootstrap Main Css =============-->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!--====== Plugins Css ================-->
    <link href="/static/css/plugins.css" rel="stylesheet">

    <!--====== Custom CSS for themes =======-->
    <link href="/static/style.css" rel="stylesheet">

    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <script src="/static/js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body>

    <!--=======Error Page
    ====================================-->
    <div class="error-page page-wrapper s-pd145">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-sm-10">
                    <div class="error-page-content">
                        <div class="not-found">403</div>
                        <h3>Access Forbidden</h3>
                        <p>CSRF verification failed. Request Aborted.</p>
                        <div class="group-btn">
                            <a href="{% url 'main:home_page' %}" class="btn btn-default btn-primary">BACK TO HOME</a>
                        </div>
                    </div><!--/.error-page-content-->
                </div><!--/.col-sm-8-->
            </div><!--/.row-->
        </div><!--/.container-->
    </div><!--/.error-page-->

    <!--=========== JS FILE DECLARATION  ==============-->
    <!-- jQuery Latest Version -->
    <script src="/static/js/jquery-v3.2.1.min.js"></script>
    <!-- PopperJS -->
    <script src="/static/js/popper.min.js"></script>
    <!-- Bootstrap framework JS -->
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- All JS plugins included in this file. -->
    <script src="/static/js/plugins.js"></script>
    <!-- Main JS file that contents all jQuery Plugins activation. -->
    <script src="/static/js/main.js"></script>
</body>

<!-- Mirrored from bdevs.net/edulab/edulab/404.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 12 May 2019 04:51:17 GMT -->
</html>

templates/staff_base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'staff/assets/vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'staff/assets/vendor/fonts/circular-std/style.css' %}">
    <link rel="stylesheet" href="{% static 'staff/assets/libs/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'staff/assets/vendor/fonts/fontawesome/css/fontawesome-all.css' %}">
    <link rel="stylesheet" href="{% static 'staff/assets/vendor/charts/chartist-bundle/chartist.css' %}">
    <link rel="stylesheet" href="{% static 'staff/assets/vendor/charts/morris-bundle/morris.css' %}">
    <link rel="stylesheet" href="{% static 'staff/assets/vendor/fonts/material-design-iconic-font/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'staff/assets/vendor/charts/c3charts/c3.css' %}">
    <link rel="stylesheet" href="{% static 'staff/assets/vendor/fonts/flag-icon-css/flag-icon.min.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/site.webmanifest' %}">

    <title>{% if title %}
        PiQuests: {{ title }}
    {% else %}
            PiQuests
    {% endif %}</title>

    <script src="{% static 'js/jquery-3.4.1.js' %}" type="text/javascript"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    </head>
<body>
    <!-- ============================================================== -->
    <!-- main wrapper -->
    <!-- ============================================================== -->
    <div class="dashboard-main-wrapper">
        <!-- ============================================================== -->
        <!-- navbar -->
        <!-- ============================================================== -->
        <div class="dashboard-header">
            <nav class="navbar navbar-expand-lg bg-white fixed-top">
                <a class="navbar-brand" href="{% url 'main:home_page' %}">
                    <img src="{% static 'images/piquests.png' %}" alt="logo" height="50">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto navbar-right-top">
                        <li class="nav-item">
                            <br>
                            <span id="time"></span>&nbsp;&nbsp;&nbsp;&nbsp;
                        </li>
                        <li class="nav-item dropdown nav-user">
                            <a class="nav-link nav-user-img" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <img src="{% static 'staff/assets/images/default-user_thumb.png' %}" alt="default-user" class="user-avatar-md rounded-circle">&nbsp;
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">
                                <div class="nav-user-info" style="background-color:#f78888">
                                    <h5 class="mb-0 text-white nav-user-name">{{ user.first_name }} {{ user.last_name }}</h5>
                                    <span class="status"></span><span class="ml-2">Available</span>
                                </div>
                                <a class="dropdown-item" href="{% url 'staff:account' %}"><i class="fas fa-user mr-2"></i>Account</a>
                                <a class="dropdown-item" href="{% url 'account_logout' %}"><i class="fas fa-power-off mr-2"></i>Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
        <!-- ============================================================== -->
        <!-- end navbar -->
        <!-- ============================================================== -->
        <!-- left sidebar -->
        <!-- ============================================================== -->
        <div class="nav-left-sidebar sidebar-dark" >
            <div class="menu-list">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="d-xl-none d-lg-none" href="#">Dashboard</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav flex-column">
                            <li class="nav-divider">
                                Menu
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link {% if sidebar == 'dashboard' %}active{% endif %}" href="{% url 'staff:dashboard' %}">
                                    <i class="fas fa-chart-line"></i>Dashboard
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if sidebar == 'course_requests' %}active{% endif %}" href="{% url 'staff:course_requests' %}">
                                    <i class="fas fa-bell"></i>Course Requests
                                    {% if course_request_count > 0 %}
                                        <sup>
                                            <span style="background-color: red; color: white; padding: 2px; border-radius: 3px;">
                                                &nbsp;<b>{{ course_request_count }}</b>&nbsp;
                                            </span>
                                        </sup>
                                    {% endif %}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if sidebar == 'course_list' %}active{% endif %}" href="{% url 'staff:course_list' %}">
                                    <i class="fas fa-fw fa-book"></i>Courses
                                </a>
                            </li>
                            {% if user.is_superuser %}
                                <li class="nav-item">
                                    <a class="nav-link {% if sidebar == 'subject_list' %}active{% endif %}" href="{% url 'staff:subject_list' %}">
                                        <i class="fas fa-puzzle-piece"></i>Subjects
                                    </a>
                                </li>
                            {% endif %}
                            {% if user.is_superuser %}
                                <li class="nav-item ">
                                    <a class="nav-link {% if sidebar == 'admin_list' %}active{% endif %}" href="{% url 'staff:admin_list' %}">
                                        <i class="fas fa-database"></i>Admin Accounts
                                    </a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a class="nav-link {% if sidebar == 'teacher_list' %}active{% endif %}" href="{% url 'staff:teacher_list' %}">
                                    <i class="fab fa-black-tie"></i>Teachers
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if sidebar == 'student_list' %}active{% endif %}" href="{% url 'staff:student_list' %}">
                                    <i class="fas fa-child"></i>Students
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% if sidebar == 'user_log' %}active{% endif %}" href="{% url 'staff:user_log_list' %}">
                                    <i class="fas fa-address-book"></i>User Log
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- wrapper  -->
        <!-- ============================================================== -->
        <div class="dashboard-wrapper">
            <div class="container-fluid dashboard-content">
                {% block content %}
                {% endblock %}
            </div>
            {% block footer %}
            {% endblock %}
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- end main wrapper  -->
    <!-- ============================================================== -->
    <script>
        var today = new Date();
        document.getElementById('time').innerHTML=today;
    </script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <!-- Optional JavaScript -->
    <!-- jquery 3.3.1 -->
    <script src="{% static 'staff/assets/vendor/jquery/jquery-3.3.1.min.js' %}" type="44c04729fd72133bc12c335c-text/javascript"></script>
    <!-- bootstap bundle js -->
    <script src="{% static 'staff/assets/vendor/bootstrap/js/bootstrap.bundle.js' %}" type="44c04729fd72133bc12c335c-text/javascript"></script>
    <!-- slimscroll js -->
    <script src="{% static 'staff/assets/vendor/slimscroll/jquery.slimscroll.js' %}" type="44c04729fd72133bc12c335c-text/javascript"></script>
    <!-- main js -->
    <script src="{% static 'staff/assets/libs/js/main-js.js' %}" type="44c04729fd72133bc12c335c-text/javascript"></script>
    <script src="https://ajax.cloudflare.com/cdn-cgi/scripts/a2bd7673/cloudflare-static/rocket-loader.min.js" data-cf-settings="44c04729fd72133bc12c335c-|49" defer=""></script>
</body>

</html>