PiQuest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from wagtail.core import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.contrib.sitemaps.views import sitemap
from puput import urls as puput_urls
from classroom.views import classroom
from digiwiz import urls as course

admin.site.site_header = 'PiQuests Admin'
admin.site.site_title = 'PiQuests Site Admin'

urlpatterns = [
    path('', include('user.urls', namespace='piquest-auth')),
    path('', include('main.urls', namespace='main')),
    path('project/', include('projects.urls', namespace='project')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('about-us/', classroom.about, name='about_us'),
    path('quiz/', include('quiz.urls', namespace='quiz')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('todo/', include('todo.urls', namespace="todo")),
    path('course/', include(course)),
    path("badges/", include("pinax.badges.urls", namespace="pinax_badges")),
    path("announcements/", include("pinax.announcements.urls", namespace="pinax_announcements")),
    path(
        route='blog_admin/',
        view=include(wagtailadmin_urls)
    ),
    path(
        route='documents/',
        view=include(wagtaildocs_urls)
    ),
    re_path(r'', include(puput_urls)),
    re_path(
        route='',
        view=include(wagtail_urls)
    ),
    path(
        route='sitemap.xml',
        view=sitemap
    ),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from .views import ContactView, ClientContactView

app_name = 'contact'


urlpatterns = [
    path('', ContactView.as_view(), name='contact'),
    path('client/', ClientContactView.as_view(), name='client-contact'),
]

main/urls.py
from django.urls import path
from .views import HomePageView, PrivacyPageView, pi_validation
from quiz.views import (CategoryDetail, CategoriesListView, CategoryCreate,
                        CategoryUpdate, CategoryDelete)

app_name = 'main'

urlpatterns = [
    path('', HomePageView.as_view(), name='home_page'),
    path('validation-key.txt', pi_validation, name='pi_validation'),
    path('privacy/', PrivacyPageView.as_view(), name='privacy_page'),
    path('category/', CategoriesListView.as_view(), name='category_list'),
    path('category/create/', CategoryCreate.as_view(), name='category_create'),
    path('category/<slug>/update/',
         CategoryUpdate.as_view(), name='category_update'),
    path('category/<slug>/delete/',
         CategoryDelete.as_view(), name='category_delete'),
    path('category/<slug>/', CategoryDetail.as_view(), name='category_detail'),
]

projects/urls.py
from django.urls import path, include
from django.conf.urls import url
from .views import (ProjectDetail, ProjectList, ArticleLinkCreate, ArticleDelete, 
ProjectCreate, ArticleUpdate, ProjectUpdate, ProjectDelete)

app_name = 'project'

urlpatterns = [
    path('', ProjectList.as_view(), name='project_list'),
    path('<slug:project_slug>/add_article_link/', ArticleLinkCreate.as_view(), name='articlelink_create'),
    path('<slug:project_slug>/<slug:articlelink_slug>/update/', ArticleUpdate.as_view(), name='articlelink_update'),
    path('<slug:project_slug>/<slug:articlelink_slug>/delete/', ArticleDelete.as_view(), name='articlelink_delete'),
    path('create/', ProjectCreate.as_view(), name='project_create'),
    path('<slug>/update/', ProjectUpdate.as_view(), name='project_update'),
    path('<slug>/delete/', ProjectDelete.as_view(), name='project_delete'),
    path('<slug>/', ProjectDetail.as_view(), name='project_detail'),
]

quiz/urls.py
from django.urls import path

from essay.views import add_essay, edit_essay, delete_essay

from multichoice.views import add_multichoice, edit_multichoice, delete_multichoice

from true_false.views import add_true_false, edit_true_false, delete_true_false

from .views import QuizListView, ViewQuizListByCategory, QuizCreateView, \
    QuizUserProgressView, QuizMarkingList, QuizDelete, publish_quiz,\
    QuizMarkingDetail, QuizDetailView, QuizTake, edit_quiz, TriviaListView, pay_quiz_winners

app_name = 'quiz'

urlpatterns = [

    path('', view=QuizListView.as_view(), name='quiz_index'),

    path('master/', view=TriviaListView.as_view(), name='master_trivia_list'),

    path('category/<slug:category_name>/',
         view=ViewQuizListByCategory.as_view(), name='quiz_category_list_matching'),

    path('progress/', view=QuizUserProgressView.as_view(), name='quiz_progress'),

    path('marking/', view=QuizMarkingList.as_view(), name='quiz_marking'),

    path('marking/<int:pk>/', view=QuizMarkingDetail.as_view(),
         name='quiz_marking_detail'),

    path('create-quiz/', QuizCreateView.as_view(), name='quiz_create'),


    #  passes variable 'quiz_name' to quiz_take view
    path('<slug>/', view=QuizDetailView.as_view(), name='quiz_start_page'),

    path('<slug>/update/', view=edit_quiz, name='quiz_update'),

    path('<slug>/delete/', view=QuizDelete.as_view(), name='quiz_delete'),

    path('<slug>/publish/', view=publish_quiz, name='publish_quiz'),

    path('<slug>/pay-winners/', view=pay_quiz_winners, name='pay_quiz_winners'),

#     path('<slug>/get-old-winners/', view=get_old_quiz_winners, name='get_old_quiz_winners'),

    path('essay/<slug>/question/add/',
         add_essay, name='essay_add'),

    path('essay/<slug>/question/<int:question_pk>/',
         edit_essay, name='essay_change'),

    path('essay/<slug>/question/<int:question_pk>/delete/',
         delete_essay, name='essay_delete'),

    path('mcq/<slug>/question/add/',
         add_multichoice, name='multichoice_add'),

    path('mcq/<slug>/question/<int:question_pk>/',
         edit_multichoice, name='multichoice_change'),

    path('mcq/<slug>/question/<int:question_pk>/delete/',
         delete_multichoice, name='multichoice_delete'),

    path('true-false/<slug>/question/add/',
         add_true_false, name='true_false_add'),

    path('true-false/<slug>/question/<int:question_pk>/',
         edit_true_false, name='true_false_change'),

    path('true-false/<slug>/question/<int:question_pk>/delete/',
         delete_true_false, name='true_false_delete'),

    path('<slug:quiz_name>/take/', view=QuizTake.as_view(), name='quiz_question'),
]

todo/urls.py
from django.conf import settings
from django.urls import path

from todo import views
from todo.features import HAS_TASK_MERGE

app_name = "todo"

urlpatterns = [
    path("", views.list_lists, name="lists"),
    # View reorder_tasks is only called by JQuery for drag/drop task ordering.
    path("reorder_tasks/", views.reorder_tasks, name="reorder_tasks"),
    # Allow users to post tasks from outside django-todo (e.g. for filing tickets - see docs)
    path("ticket/add/", views.external_add, name="external_add"),
    # Three paths into `list_detail` view
    path("mine/", views.list_detail, {"list_slug": "mine"}, name="mine"),
    path(
        "<int:list_id>/<str:list_slug>/completed/",
        views.list_detail,
        {"view_completed": True},
        name="list_detail_completed",
    ),
    path("<int:list_id>/<str:list_slug>/", views.list_detail, name="list_detail"),
    path("<int:list_id>/<str:list_slug>/delete/", views.del_list, name="del_list"),
    path("add_list/", views.add_list, name="add_list"),
    path("task/<int:task_id>/", views.task_detail, name="task_detail"),
    path(
        "attachment/remove/<int:attachment_id>/", views.remove_attachment, name="remove_attachment"
    ),
]

if HAS_TASK_MERGE:
    # ensure mail tracker autocomplete is optional
    from todo.views.task_autocomplete import TaskAutocomplete

    urlpatterns.append(
        path(
            "task/<int:task_id>/autocomplete/", TaskAutocomplete.as_view(), name="task_autocomplete"
        )
    )

urlpatterns.extend(
    [
        path("toggle_done/<int:task_id>/", views.toggle_done, name="task_toggle_done"),
        path("delete/<int:task_id>/", views.delete_task, name="delete_task"),
        path("search/", views.search, name="search"),
        path("import_csv/", views.import_csv, name="import_csv"),
    ]
)

main/models.py
# from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.exceptions import MultipleObjectsReturned
from pinax.badges.base import Badge, BadgeAwarded
from pinax.badges.registry import badges
import quiz.models as qm


# Create your models here.
class WinnerBadge(Badge):
    slug = "winnings"
    levels = ["Winner", ]
    events = [
        "mark_quiz_complete",
    ]
    multiple = True

    def award(self, **state):
        user = state["user"]
        try:
            if_passed = qm.Sitting.objects.get(user=user).check_if_passed
            if_complete = qm.Sitting.objects.get(user=user).complete
        except MultipleObjectsReturned:
            if_passed = qm.Sitting.objects.filter(
                user=user).first().check_if_passed
            if_complete = qm.Sitting.objects.filter(user=user).first().complete
        if(if_passed and if_complete):
            return BadgeAwarded()


badges.register(WinnerBadge)


# class User(AbstractUser):
#     pass


# class Creator(models.Model):

#     PUBLIC_CHAIN_CHOICES = (
#         ('Ethereum', 'Ethereum'),
#         ('Binance Smart Chain', 'Binance Smart Chain'),
#         ('Neo', 'Neo'),
#         ('Waves', 'Waves'),
#         ('Pi Network', 'PiNetwork'),
#     )

#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     wallet_address = models.CharField(max_length=50)
#     telegram_id = models.CharField(max_length=50)
#     twitter_id = models.CharField(max_length=50)
#     public_chain = models.CharField(choices=PUBLIC_CHAIN_CHOICES ,max_length=50)

#     def __str__(self):
#         return self.telegram_id


# class Taker(models.Model):

#     PUBLIC_CHAIN_CHOICES = (
#         ('Ethereum', 'Ethereum'),
#         ('Binance Smart Chain', 'Binance Smart Chain'),
#         ('Neo', 'Neo'),
#         ('Waves', 'Waves'),
#         ('Pi Network', 'PiNetwork'),
#     )

#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     wallet_address = models.CharField(max_length=50)
#     telegram_id = models.CharField(max_length=50)
#     twitter_id = models.CharField(max_length=50)
#     public_chain = models.CharField(choices=PUBLIC_CHAIN_CHOICES ,max_length=50)

#     def __str__(self):
#         return f"{self.user.first_name} {self.user.last_name}"

main/views.py
from django.http.response import HttpResponse
from django.template import Context, loader
from django.shortcuts import render
from django.views.generic import TemplateView
from django.conf import settings
from coinmarketcapapi import CoinMarketCapAPI, CoinMarketCapAPIError


# Create your views here.
cmc = CoinMarketCapAPI(settings.CMC_PRO_API_KEY)


class HomePageView(TemplateView):
    template_name = 'main/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        r = cmc.cryptocurrency_quotes_latest(
            symbol='BTC,ETH,BNB,DOGE,WAVES,XRP,ADA,AXS')
        if not r.error:
            nested_dictionary = r.data
            context['crypto_context'] = nested_dictionary
        return context


class PrivacyPageView(TemplateView):
    template_name = 'main/privacy_policy.html'


def pi_validation(request):
    filename = "validation-key.txt"
    content = settings.PI_VALIDATION_KEY
    response = HttpResponse(content, content_type='text/plain')
    response['Content-Disposition'] = 'attachment; filename={0}'.format(
        filename)
    return response

main/templates/main/category_confirm_delete.html
{% extends parent_template|default:"projects/base_projects.html" %}

{% block title %}
Delete Category
{% endblock %}

{% block content %}
<section class="text-gray-600 body-font">
<div class="container px-5 py-24 mx-auto">
    <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
        <form action="{{ category.get_delete_url }}" method="post">
            {% csrf_token %}
            <h1 class="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">Are you sure you want to delete "{{ category.category }}" category</h1>
            <div class="inline-block mr-2 mt-2">
                <button type="submit" class="focus:outline-none text-red-600 text-sm py-2.5 px-5 rounded-full border border-red-600 hover:bg-red-50">Delete</button>
            </div>
            <div class="inline-block mr-2 mt-2">
                <button type="button" class="focus:outline-none text-blue-600 text-sm py-2.5 px-5 rounded-md hover:bg-blue-100"><a href="{{ category.get_absolute_url }}">Cancel</a></button>
            </div>
            </form>
    </div>
</div>
</section>
{% endblock %}

main/templates/main/category_create_form.html
{% extends parent_template|default:"base_contact.html" %}
{% load tailwind_filters %}

{% block title %}
Create Category
{% endblock %}
{% block form_heading %}Create Category{% endblock %}
{% block form_sub_heading %}Fill up the form below to create a category{% endblock form_sub_heading %}
{% block form_content %}
        <form action="{% url 'main:category_create' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full px-3 py-4 text-white bg-indigo-500 rounded-md focus:bg-indigo-600 focus:outline-none">Create Category</button>
        </form>
{% endblock form_content %}

main/templates/main/category_update_form.html
{% extends parent_template|default:"base_contact.html" %}
{% load tailwind_filters %}

{% block title %}
Update {{ category.category }}
{% endblock %}
{% block form_heading %}Update {{ category.category }}{% endblock %}
{% block form_sub_heading %}Fill up the form below to update this category{% endblock form_sub_heading %}
{% block form_content %}
        <form action="{{ category.get_update_url }}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="w-full px-3 py-4 text-white bg-indigo-500 rounded-md focus:bg-indigo-600 focus:outline-none" type="submit">Update Category</button>
        </form>
{% endblock %}

main/templates/main/classroom-footer.html
{% load static %}
<footer id="dk-footer" class="dk-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-4">
                    <div class="dk-footer-box-info">
                        <a href="{% url 'main:home_page' %}" class="footer-logo">
                            <img src="{% static 'images/piquests.png' %}" alt="piquests" class="img-fluid">
                        </a>
                        <p class="footer-info-text">
                            Connect and learn about businesses around you, and get crypto rewards by proving your knowledge.
                        </p>
                        <div class="footer-social-link">
                            <h3>Follow us</h3>
                            <ul>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-facebook"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-twitter"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-google-plus"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-linkedin"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- End Social link -->
                    </div>
                    <!-- End Footer info -->
                    <div class="footer-awarad">
                        <img src="images/icon/best.png" alt="">
                        <p>Learn, Earn, Create...</p>
                    </div>
                </div>
                <!-- End Col -->
                <div class="col-md-12 col-lg-8">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="contact-us">
                                <div class="contact-icon">
                                    <i class="fa fa-map-o" aria-hidden="true"></i>
                                </div>
                                <!-- End contact Icon -->
                                <div class="contact-info">
                                    <h3>Lagos Nigeria</h3>
                                    <p>Surulere</p>
                                </div>
                                <!-- End Contact Info -->
                            </div>
                            <!-- End Contact Us -->
                        </div>
                        <!-- End Col -->
                        <div class="col-md-6">
                            <div class="contact-us contact-us-last">
                                <div class="contact-icon">
                                    <i class="fa fa-volume-control-phone" aria-hidden="true"></i>
                                </div>
                                <!-- End contact Icon -->
                                <div class="contact-info">
                                    <h3>+234 807 478 9552</h3>
                                    <p>For Enquiries</p>
                                </div>
                                <!-- End Contact Info -->
                            </div>
                            <!-- End Contact Us -->
                        </div>
                        <!-- End Col -->
                    </div>
                    <!-- End Contact Row -->
                    <div class="row">
                        <div class="col-md-12 col-lg-6">
                            <div class="footer-widget footer-left-widget">
                                <div class="section-heading">
                                    <h3>Useful Links</h3>
                                    <span class="animate-border border-black"></span>
                                </div>
                                <ul>
                                    <li>
                                        <a href="{% url 'about_us' %}">About us</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'quiz:quiz_index' %}">Trivia</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'home' %}">Learn</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'project:project_list' %}">Our Partners</a>
                                    </li>
                                </ul>
                                <ul>
                                    <li>
                                        <a href="{% url 'contact:contact' %}">Contact us</a>
                                    </li>
                                    <li>
                                        <a href="/blog">Blog</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'main:category_list' %}">Interests</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'main:privacy_page' %}">Privacy Policy</a>
                                    </li>
                                </ul>
                            </div>
                            <!-- End Footer Widget -->
                        </div>
                        <!-- End col -->
                        <div class="col-md-12 col-lg-6">
                            <div class="footer-widget">
                                <div class="section-heading">
                                    <h3>Subscribe</h3>
                                    <span class="animate-border border-black"></span>
                                </div>
                                <p><!-- Don’t miss to subscribe to our new feeds, kindly fill the form below. -->
                                Coming soon!!!</p>
                                <form action="#">
                                    <div class="form-row">
                                        <div class="col dk-footer-form">
                                            <input type="email" class="form-control" placeholder="Email Address">
                                            <button type="submit">
                                                <i class="fa fa-send"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                                <!-- End form -->
                            </div>
                            <!-- End footer widget -->
                        </div>
                        <!-- End Col -->
                    </div>
                    <!-- End Row -->
                </div>
                <!-- End Col -->
            </div>
            <!-- End Widget Row -->
        </div>
        <!-- End Contact Container -->


        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <span>Copyright © 2021, All Right Reserved KunJon</span>
                    </div>
                    <!-- End Col -->
                    <div class="col-md-6">
                        <div class="copyright-menu">
                            <ul>
                                <li>
                                    <a href="{% url 'main:home_page' %}">Home</a>
                                </li>
                                <li>
                                    <a href="{% url 'quiz:quiz_index' %}">Trivia</a>
                                </li>
                                <li>
                                    <a href="{% url 'main:privacy_page' %}">Privacy Policy</a>
                                </li>
                                <li>
                                    <a href="{% url 'contact:contact' %}">Contact</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- End col -->
                </div>
                <!-- End Row -->
            </div>
            <!-- End Copyright Container -->
        </div>
        <!-- End Copyright -->
</footer>

main/templates/main/footer.html
{% load static %}
<footer class="bg-gray-50 text-gray-600 px-6 lg:px-8 py-12">
  <div class="min-h-screen-xl flex items-start mx-auto mb-10 lg:mb-12">
    <a href="{% url 'main:home_page' %}"><img src="{% static 'images/piquests.png' %}" alt="piquests" class="w-48"></a>
  </div>
  <div class="max-w-screen-xl mx-auto ">
    <div class="grid grid-cols-8 md:grid-cols-9  lg:grid-cols-8  divide-languid-lavender divide-y-2 md:divide-x-2 md:divide-y-0 md:-mx-8">
      <div class="col-span-8 md:col-span-3 lg:col-span-2 md:px-8 py-4 md:py-0">
        <h5 class="text-xl font-semibold text-gray-700">PiQuests</h5>
        <nav class="mt-4">
          <ul class="space-y-2">
            <li>
              <a href="{% url 'main:home_page' %}" class="font-normal text-base hover:text-gray-400">Home</a>
            </li>
            <li>
              <a href="{% url 'contact:contact' %}" class="font-normal text-base hover:text-gray-400">Contact Us</a>
            </li>
            <li>
              <a href="{% url 'home' %}" class="font-normal text-base hover:text-gray-400">Learn</a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="col-span-8 md:col-span-3 lg:col-span-3 md:px-8 py-4 md:py-0">
        <h5 class="text-xl font-semibold text-gray-700">Links</h5>
        <nav class="mt-4">
          <ul class="grid lg:grid-cols-2">
            <li class="mb-2">
              <a href="{% url 'quiz:quiz_index' %}" class="font-normal text-base hover:text-gray-400">Trivia</a>
            </li>
            <li class="mb-2">
              <a href="{% url 'about_us' %}" class="font-normal text-base hover:text-gray-400">About us</a>
            </li>
            <li class="mb-2">
              <a href="{% url 'main:category_list' %}" class="font-normal text-base hover:text-gray-400">Interests</a>
            </li>
            <li class="mb-2">
              <a href="/blog" class="font-normal text-base hover:text-gray-400">Blog</a>
            </li>
          </ul>
        </nav>
      </div>
      <div class="col-span-8 md:col-span-3 lg:col-span-3 md:px-8 py-4 md:py-0">
        <h5 class="text-xl font-semibold text-gray-700">Follow us</h5>
        <nav class="mt-4">
          <ul class="grid lg:grid-cols-2">
            <li class="mb-2">
              <a href="#" class="flex space-x-2 font-normal text-base hover:text-gray-400">
                <svg class="h-6 w-6" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
                </svg>
                <span>
                  Twitter
                </span>
              </a>
            </li>
            <li class="mb-2">
              <a href="#" class="flex space-x-2  font-normal text-base hover:text-gray-400">
                <svg class="h-6 w-6" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24">
                  <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" />
                </svg>
                <span>
                  Instagram
                </span>
              </a>
            </li>
            <li class="mb-2">
              <a href="#" class="flex space-x-2  font-normal text-base hover:text-gray-400">
                <svg class="h-6 w-6" aria-hidden="true" fill="currentColor" viewBox="0 0 24 24">
                  <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" />
                </svg>
                <span>
                  Facebook
                </span>
              </a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
  <div class="max-w-screen-xl mx-auto flex flex-col md:flex-row justify-between items-center space-y-4 mt-8 lg:mt-12 border-t-2 border-languid-lavender pt-8">
    <nav class="flex flex-wrap justify-center space-x-6"> 
      <a href="{% url 'main:privacy_page' %}" class="font-normal text-sm hover:text-gray-400 mb-2">Privacy policies</a>
    </nav>
    <p class="text-sm text-center md:text-right">&copy;2021 PiQuests. All rights reserved. | All rights reserved</p>
  </div>
</footer>